import type { Metadata } from 'next';
import { LegalPage, LegalSection } from '@/components/LegalPage';

export const metadata: Metadata = {
  title: 'Terms of Service — NODAL',
  description: 'The terms under which you may use NODAL to report civic issues.',
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      intro="By using NODAL, you agree to these terms. They are written to be readable, not to trick you."
      updated="28 June 2026"
    >
      <LegalSection heading="What NODAL does">
        <p>NODAL helps you document a civic issue, classifies it with AI, routes it to the appropriate municipal department, and drafts formal notices (complaint, RTI, and accessibility grievance). NODAL dispatches these notices by email; in the current demo deployment they are routed to a test inbox, and you can also send them yourself from your own email.</p>
      </LegalSection>

      <LegalSection heading="Your responsibilities">
        <ul>
          <li>Submit only <strong>genuine, accurate</strong> reports of real civic issues.</li>
          <li>Do not upload photos that are unlawful, defamatory, or that infringe others&apos; privacy or rights.</li>
          <li>Do not misuse the platform to harass individuals or file false complaints.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="No guarantee of government action">
        <p>NODAL is an independent civic tool, not a government service. We draft and help you dispatch notices, but we cannot guarantee that any authority will respond or resolve your issue. Statuses such as &quot;Notice Sent&quot; reflect your action, not confirmed delivery or resolution.</p>
      </LegalSection>

      <LegalSection heading="AI-generated content">
        <p>Classifications and drafted notices are generated by AI and may contain errors. Review every notice before you send it. You are responsible for the content you dispatch.</p>
      </LegalSection>

      <LegalSection heading="Limitation of liability">
        <p>NODAL is provided &quot;as is&quot;, without warranties. To the extent permitted by law, we are not liable for any loss arising from your use of the platform or from actions (or inaction) by third parties or authorities.</p>
      </LegalSection>

      <LegalSection heading="Governing law">
        <p>These terms are governed by the laws of India.</p>
      </LegalSection>

      <LegalSection heading="Contact">
        <p>Questions? Email <a href="mailto:mukesh.r240108@gmail.com">mukesh.r240108@gmail.com</a>.</p>
      </LegalSection>
    </LegalPage>
  );
}
